# Generated by Django 5.0.6 on 2025-04-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuID', models.CharField(max_length=50)),
                ('stuName', models.CharField(max_length=50)),
                ('stuDep', models.CharField(max_length=50)),
            ],
        ),
    ]
